/**
 * Invariant 5: frontend allocation preview matches backend.
 *
 * Loads `tests/fixtures/allocation-cases.json` (generated by
 * scripts/generate_allocation_parity_fixture.py) and runs each case through
 * the JS allocation-preview library, asserting numeric parity with the
 * Python reference output.
 *
 * Regenerate the fixture whenever the backend allocation engine changes:
 *
 *   python scripts/generate_allocation_parity_fixture.py
 */

import { describe, expect, it } from "vitest";

import fixture from "./fixtures/allocation-cases.json";
import { computeAllocation, validatePreferences } from "../lib/allocation-preview";
import type { ChapterSnapshot } from "../lib/types";

const TOLERANCE = 1e-6;
const chapters = fixture.chapters as ChapterSnapshot[];

describe("allocation-preview parity with Python backend", () => {
  for (const testCase of fixture.cases) {
    it(`matches Python output for ${testCase.label}`, () => {
      const result = computeAllocation(
        chapters,
        testCase.preferences,
        testCase.amount_eur,
      );

      for (const expected of testCase.expected) {
        const actual = result[expected.chapter_id];
        expect(actual).toBeDefined();
        expect(Math.abs(actual.weight - expected.weight)).toBeLessThan(TOLERANCE);
        expect(Math.abs(actual.amount_eur - expected.amount_eur)).toBeLessThan(
          TOLERANCE * Math.max(1, Math.abs(expected.amount_eur)),
        );
        expect(
          Math.abs(actual.axis_weights.climate - expected.axis_weights.climate),
        ).toBeLessThan(TOLERANCE);
        expect(
          Math.abs(actual.axis_weights.social - expected.axis_weights.social),
        ).toBeLessThan(TOLERANCE);
        expect(
          Math.abs(actual.axis_weights.balanced - expected.axis_weights.balanced),
        ).toBeLessThan(TOLERANCE);
      }
    });
  }
});

describe("validatePreferences", () => {
  it("accepts valid preferences", () => {
    expect(() =>
      validatePreferences({
        max_climate_impact: 0.4,
        max_social_need: 0.4,
        balanced_distribution: 0.2,
      }),
    ).not.toThrow();
  });

  it("rejects preferences that don't sum to 1", () => {
    expect(() =>
      validatePreferences({
        max_climate_impact: 0.5,
        max_social_need: 0.4,
        balanced_distribution: 0.4,
      }),
    ).toThrow(/sum to 1/);
  });
});
