import Link from "next/link";
import { promises as fs } from "fs";
import path from "path";
import { notFound } from "next/navigation";
import { marked } from "marked";
import { loadBanks } from "@/lib/banks";

export default async function ReportPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const data = await loadBanks();
  const bank = data.banks.find((b) => b.id === id);
  if (!bank) notFound();

  // Hardcoded to Q2 2026 for the demo. In production this would be
  // dynamic based on the corporate's package start date and quarterly cadence.
  const reportPath = path.join(
    process.cwd(),
    "public",
    "reports",
    `${bank.id}-q2-2026.md`
  );

  let markdown: string | null = null;
  try {
    markdown = await fs.readFile(reportPath, "utf-8");
  } catch {
    markdown = null;
  }

  if (!markdown) {
    return (
      <div className="mx-auto max-w-3xl px-6 py-12">
        <Link
          href={`/banks/${bank.id}`}
          className="text-sm text-stone-500 hover:text-stone-900 inline-flex items-center gap-1"
        >
          ← Back to {bank.name}
        </Link>
        <div className="mt-6 rounded-xl border border-amber-200 bg-amber-50 p-6">
          <h1 className="text-xl font-semibold text-amber-900">
            Report not yet generated
          </h1>
          <p className="mt-2 text-sm text-amber-800 leading-relaxed">
            This bank&apos;s Q2 2026 report has not been generated yet. The
            production pipeline runs the FRAME calculator and Claude
            report-generator on a quarterly cadence; this demo build only
            ships with the Rotterdam Q2 2026 report pre-generated.
          </p>
        </div>
      </div>
    );
  }

  const html = marked.parse(markdown, { gfm: true, breaks: false });

  return (
    <div className="mx-auto max-w-4xl px-6 py-10">
      <div className="flex items-center justify-between mb-6">
        <Link
          href={`/banks/${bank.id}/buy/confirmed`}
          className="text-sm text-stone-500 hover:text-stone-900 inline-flex items-center gap-1"
        >
          ← Back to confirmation
        </Link>
        <div className="flex gap-3">
          <a
            href={`/reports/${bank.id}-q2-2026.md`}
            download
            className="text-sm rounded-lg border border-stone-300 hover:border-stone-400 text-stone-700 font-medium px-3 py-1.5 transition-colors"
          >
            Download .md
          </a>
        </div>
      </div>

      <article
        className="prose-report rounded-xl border border-stone-200 bg-white p-10 shadow-sm"
        dangerouslySetInnerHTML={{ __html: html }}
      />

      <p className="mt-6 text-center text-xs text-stone-500">
        Generated by the Climate-Action Packages platform · methodology aligned
        with the Global Foodbanking Network FRAME framework
      </p>
    </div>
  );
}
