"use client"

import { useState } from "react"
import { useRouter } from "next/navigation"
import Link from "next/link"
import { Button } from "@/components/ui/Button"
import { Badge } from "@/components/ui/Badge"
import { api } from "@/lib/api"

export function ReportCard({
  subId,
  hasReport,
}: {
  subId: string
  hasReport: boolean
}) {
  const router = useRouter()
  const [busy, setBusy] = useState(false)

  async function onGenerate() {
    setBusy(true)
    await api.generateReport(subId).catch(() => null)
    router.push(`/reports/${subId}`)
  }

  return (
    <div className="border border-line rounded-[var(--radius-lg)] bg-emerald-soft/50 p-7">
      <div className="flex items-center gap-2 mb-4 flex-wrap">
        <Badge variant="emerald">Disclosure-ready</Badge>
        <Badge variant="outline">ESRS E5</Badge>
        <Badge variant="outline">ESRS S3</Badge>
        <Badge variant="outline">Contribution claim</Badge>
      </div>
      <h3 className="display text-2xl tracking-[-0.02em] max-w-[28ch]">
        Annual contribution disclosure.
      </h3>
      <p className="text-text-muted text-[13.5px] mt-3 max-w-[44ch] leading-relaxed">
        Generated from the FRAME workings, allocation breakdown,
        and source citations of every food bank in your portfolio.
      </p>

      <ul className="mt-5 grid sm:grid-cols-2 gap-x-4 gap-y-1.5 text-[13px]">
        <Item>E1-1 Climate transition plan</Item>
        <Item>E1-4 GHG reduction targets</Item>
        <Item>E1-6 Gross Scope 3 emissions</Item>
        <Item>S3-1 Material impacts</Item>
        <Item>S3-4 Channels for engagement</Item>
        <Item>FRAME methodology workings</Item>
      </ul>

      <div className="mt-7 flex items-center gap-3 flex-wrap">
        {hasReport ? (
          <Link
            href={`/reports/${subId}`}
            className="bg-emerald text-text-on-emerald h-10 px-4 inline-flex items-center text-[13.5px] font-medium"
          >
            View full report →
          </Link>
        ) : (
          <Button onClick={onGenerate} disabled={busy}>
            {busy ? "Starting…" : "Generate report"}
          </Button>
        )}
        <Link
          href={`/api/report/${subId}/download`}
          className="text-[13.5px] text-emerald-deep hover:underline"
        >
          Download .md
        </Link>
        <span className="text-[12px] text-text-faint tabular ml-auto">
          generated by claude-sonnet-4-6
        </span>
      </div>
    </div>
  )
}

function Item({ children }: { children: React.ReactNode }) {
  return (
    <li className="flex items-start gap-2">
      <span aria-hidden className="mt-1.5 block w-1.5 h-1.5 rounded-full bg-emerald-deep shrink-0" />
      <span>{children}</span>
    </li>
  )
}
