from fastapi import FastAPI, Request, Response
from starlette.middleware.base import BaseHTTPMiddleware

from src.backend.database import create_db_and_tables
from src.backend.routers import auth as auth_router
from src.backend.routers import marketplace as marketplace_router
from src.backend.routers import checkout as checkout_router
from src.backend.routers import dashboard as dashboard_router
from src.backend.routers import admin as admin_router
from src.backend.routers import report as report_router
from src.backend.routers import insights as insights_router
from src.backend.routers import discovery as discovery_router
from src.backend.routers import profiles as profiles_router
from src.backend.routers import foodbanks as foodbanks_router

OPENAPI_TAGS = [
    {"name": "discovery", "description": "Agent/LLM discovery: health, llms.txt, robots.txt, manifests"},
    {"name": "auth", "description": "Registration, login, logout, current user"},
    {"name": "packages", "description": "Browse available climate impact packages (public)"},
    {"name": "checkout", "description": "Subscribe to a package and confirm payment"},
    {"name": "dashboard", "description": "Your subscriptions with CO₂e attribution per foodbank"},
    {"name": "report", "description": "Generate, stream, and download CSRD/ESRS E5 reports"},
    {"name": "insights", "description": "Public platform stats and per-foodbank FRAME data"},
    {"name": "admin", "description": "Admin-only: foodbank management"},
    {"name": "profiles", "description": "Impact allocation profiles (public read, admin write)"},
    {"name": "foodbanks", "description": "Foodbank transparency profiles + multi-year timelines"},
]

app = FastAPI(
    title="Climate Harvest",
    version="1.0.0",
    summary="Dutch platform connecting corporates to foodbank climate impact funds.",
    description=(
        "Corporates subscribe to impact packages. Funds are allocated to Dutch foodbanks "
        "weighted by verified CO₂e savings (FRAME methodology) and households served. "
        "CSRD/ESRS E5-compliant reports are generated by Claude Sonnet and streamed as SSE.\n\n"
        "**Public endpoints:** `/packages`, `/insights/aggregate`, `/insights/banks`, `/foodbanks`\n\n"
        "**Authentication:** Cookie session via `POST /auth/login`. "
        "Register at `POST /auth/register`.\n\n"
        "**Agent discovery:** [`/llms.txt`](/llms.txt) · "
        "[`/.well-known/ai-plugin.json`](/.well-known/ai-plugin.json)"
    ),
    contact={"name": "Climate Harvest", "email": "contact@klimaatkracht.nl"},
    license_info={"name": "Proprietary"},
    openapi_tags=OPENAPI_TAGS,
)


class AgentDiscoveryMiddleware(BaseHTTPMiddleware):
    """Add Link header pointing to llms.txt on all responses."""

    async def dispatch(self, request: Request, call_next) -> Response:
        response = await call_next(request)
        response.headers["Link"] = '</llms.txt>; rel="describedby"; type="text/plain"'
        return response


app.add_middleware(AgentDiscoveryMiddleware)


@app.on_event("startup")
def on_startup():
    create_db_and_tables()


app.include_router(discovery_router.router)
app.include_router(auth_router.router)
app.include_router(marketplace_router.router)
app.include_router(checkout_router.router)
app.include_router(dashboard_router.router)
app.include_router(admin_router.router)
app.include_router(report_router.router)
app.include_router(insights_router.router)
app.include_router(profiles_router.router)
app.include_router(foodbanks_router.router)
