import Link from "next/link";
import { notFound } from "next/navigation";
import { loadBanks, formatEuros, formatNumber } from "@/lib/banks";

export default async function ConfirmedPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;
  const data = await loadBanks();
  const bank = data.banks.find((b) => b.id === id);
  if (!bank) notFound();

  const sp = bank.standard_package;

  return (
    <div className="mx-auto max-w-3xl px-6 py-12">
      <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-6 mb-8">
        <div className="flex items-center gap-3">
          <span className="inline-flex h-8 w-8 items-center justify-center rounded-full bg-emerald-700 text-white text-lg">
            ✓
          </span>
          <div>
            <p className="text-sm font-semibold text-emerald-900">
              Sponsorship confirmed
            </p>
            <p className="text-sm text-emerald-800">
              {formatEuros(sp.amount_eur)} routed to {bank.name} · receipt sent
              to your email
            </p>
          </div>
        </div>
      </div>

      <div className="rounded-xl border border-stone-200 bg-white p-6 mb-6">
        <p className="text-xs uppercase tracking-widest text-emerald-800 font-semibold">
          Q2 2026 impact
        </p>
        <div className="mt-3 grid grid-cols-2 gap-6">
          <div>
            <p className="text-xs text-stone-500">Avoided emissions</p>
            <p className="text-3xl font-semibold tabular-nums text-stone-900 mt-0.5">
              {formatNumber(sp.attributed_tco2e)}
              <span className="text-base font-normal text-stone-500 ml-1">
                tCO<sub>2</sub>e
              </span>
            </p>
          </div>
          <div>
            <p className="text-xs text-stone-500">Food rescued</p>
            <p className="text-3xl font-semibold tabular-nums text-stone-900 mt-0.5">
              {formatNumber(sp.attributed_kg_food)}
              <span className="text-base font-normal text-stone-500 ml-1">kg</span>
            </p>
          </div>
        </div>
      </div>

      <div className="rounded-xl border border-stone-200 bg-white p-6">
        <h2 className="text-lg font-semibold tracking-tight text-stone-900 mb-2">
          Your audit-ready report is ready
        </h2>
        <p className="text-sm text-stone-600 leading-relaxed">
          Generated by Claude under FRAME-aligned methodology. Sections map
          directly to CSRD ESRS E1 (climate change) and ESRS S3 (affected
          communities). Drop straight into your sustainability statement, or
          forward to your auditor.
        </p>
        <div className="mt-5 flex flex-wrap gap-3">
          <Link
            href={`/banks/${bank.id}/report`}
            className="rounded-lg bg-emerald-900 hover:bg-emerald-800 text-white font-medium px-5 py-2.5 transition-colors"
          >
            View Q2 2026 report
          </Link>
          <Link
            href="/"
            className="rounded-lg border border-stone-300 hover:border-stone-400 text-stone-700 font-medium px-5 py-2.5 transition-colors"
          >
            Back to marketplace
          </Link>
        </div>
      </div>
    </div>
  );
}
