"""add_lat_lng_to_foodbank

Revision ID: 0aec2e488339
Revises: 
Create Date: 2026-04-25 21:02:05.849274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0aec2e488339'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('csrreport', schema=None) as batch_op:
        batch_op.alter_column('frame_result_id',
               existing_type=sa.CHAR(length=32),
               nullable=True)

    with op.batch_alter_table('foodbank', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lng', sa.Float(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.Enum('corporate', 'foodbank', 'admin', name='roleenum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('role',
               existing_type=sa.Enum('corporate', 'foodbank', 'admin', name='roleenum'),
               type_=sa.VARCHAR(length=11),
               existing_nullable=False)

    with op.batch_alter_table('foodbank', schema=None) as batch_op:
        batch_op.drop_column('lng')
        batch_op.drop_column('lat')

    with op.batch_alter_table('csrreport', schema=None) as batch_op:
        batch_op.alter_column('frame_result_id',
               existing_type=sa.CHAR(length=32),
               nullable=False)

    # ### end Alembic commands ###
