"""frame_full_methodology_fields

Revision ID: 53f79aae0572
Revises: efc871ed6f2b
Create Date: 2026-04-26 00:28:41.199211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '53f79aae0572'
down_revision: Union[str, Sequence[str], None] = 'efc871ed6f2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('frameresult', schema=None) as batch_op:
        batch_op.add_column(sa.Column('baseline_co2e_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('leakage_co2e_kg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('avoided_co2e_kg', sa.Float(), nullable=True))

    with op.batch_alter_table('ingestionrecord', schema=None) as batch_op:
        batch_op.alter_column('missing_fields',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingestionrecord', schema=None) as batch_op:
        batch_op.alter_column('missing_fields',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('frameresult', schema=None) as batch_op:
        batch_op.drop_column('avoided_co2e_kg')
        batch_op.drop_column('leakage_co2e_kg')
        batch_op.drop_column('baseline_co2e_kg')

    # ### end Alembic commands ###
