"""foodbank_location_table

Revision ID: fb55d1beb0e3
Revises: 0aec2e488339
Create Date: 2026-04-25 21:10:08.812189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'fb55d1beb0e3'
down_revision: Union[str, Sequence[str], None] = '0aec2e488339'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('foodbanklocation',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('foodbank_id', sa.Uuid(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('geocoded_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['foodbank_id'], ['foodbank.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('foodbanklocation', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_foodbanklocation_foodbank_id'), ['foodbank_id'], unique=True)

    op.create_table('ingestionrecord',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('bank_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('model', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'done', 'failed', 'skipped', name='ingestionstatus'), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(length=2000), nullable=True),
    sa.Column('report_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['annualreport.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ingestionrecord', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ingestionrecord_file_path'), ['file_path'], unique=True)

    with op.batch_alter_table('foodbank', schema=None) as batch_op:
        batch_op.drop_column('lat')
        batch_op.drop_column('lng')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foodbank', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lng', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('lat', sa.FLOAT(), nullable=True))

    with op.batch_alter_table('ingestionrecord', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ingestionrecord_file_path'))

    op.drop_table('ingestionrecord')
    with op.batch_alter_table('foodbanklocation', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_foodbanklocation_foodbank_id'))

    op.drop_table('foodbanklocation')
    # ### end Alembic commands ###
