"""
Generate scratch pitch video — six title-card frames + TTS voiceover + burned subtitles.

Honesty: this is a placeholder. The team replaces the visuals with real screen
recordings of the Next.js marketplace before the Sunday submission.

Run: .venv/bin/python video/build.py
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path
from PIL import Image, ImageDraw, ImageFont

ROOT = Path(__file__).parent
FRAMES_DIR = ROOT / "frames"
AUDIO_DIR = ROOT / "audio"
W, H = 640, 360

# Font paths (macOS system fonts)
FONT_BOLD = "/System/Library/Fonts/Helvetica.ttc"
FONT_REG = "/System/Library/Fonts/Helvetica.ttc"
FONT_MONO = "/System/Library/Fonts/Menlo.ttc"


def font(size: int, bold: bool = False) -> ImageFont.FreeTypeFont:
    # Helvetica.ttc has Bold at index 1 on macOS
    return ImageFont.truetype(FONT_BOLD, size, index=1 if bold else 0)


def text_size(draw: ImageDraw.ImageDraw, txt: str, fnt) -> tuple[int, int]:
    bbox = draw.textbbox((0, 0), txt, font=fnt)
    return bbox[2] - bbox[0], bbox[3] - bbox[1]


def centered(draw, y: int, txt: str, fnt, fill: str) -> None:
    w, _ = text_size(draw, txt, fnt)
    draw.text(((W - w) // 2, y), txt, fill=fill, font=fnt)


def frame(path: Path, draws) -> None:
    img = Image.new("RGB", (W, H), "#0c1420")
    d = ImageDraw.Draw(img)
    for fn in draws:
        fn(d)
    img.save(path)


# Color palette
NAVY = "#0c1420"
EMERALD = "#065f46"
DARK_EMERALD = "#022c22"
CREAM = "#fafaf9"
WHITE = "#ffffff"
RED = "#dc2626"
AMBER = "#f59e0b"
STONE = "#a8a29e"


def scene_1_hook():
    img = Image.new("RGB", (W, H), NAVY)
    d = ImageDraw.Draw(img)
    centered(d, 80, "Every CSR climate disclosure", font(20), STONE)
    centered(d, 130, "filed under CSRD in 2026.", font(20), STONE)
    # Big red stamp
    centered(d, 195, "UNVERIFIED", font(56, bold=True), RED)
    centered(d, 285, "Greenwashing dressed up as compliance.", font(16), STONE)
    img.save(FRAMES_DIR / "01-hook.png")


def scene_2_insight():
    img = Image.new("RGB", (W, H), DARK_EMERALD)
    d = ImageDraw.Draw(img)
    centered(d, 60, "DUTCH FOODBANKS  |  2024", font(13, bold=True), STONE)
    centered(d, 105, "40,000,000", font(72, bold=True), WHITE)
    centered(d, 185, "kg of food rescued from waste each year", font(18), CREAM)
    centered(d, 235, "≈ 100,000 tCO₂e avoided", font(18, bold=True), "#86efac")
    centered(d, 285, "None of it shows up on a single CSR report.", font(15), STONE)
    img.save(FRAMES_DIR / "02-insight.png")


def scene_3_product():
    img = Image.new("RGB", (W, H), CREAM)
    d = ImageDraw.Draw(img)
    centered(d, 50, "CLIMATE-ACTION PACKAGES", font(13, bold=True), EMERALD)
    centered(d, 95, "€25,000 = 600 tCO₂e", font(40, bold=True), "#0c0a09")
    centered(d, 160, "verified avoided emissions, tied to a specific Dutch foodbank", font(14), "#57534e")
    # Two-column row
    d.line([(W // 2, 200), (W // 2, 290)], fill="#e7e5e4", width=1)
    centered_in_col(d, "CORPORATES", "buy verified impact", 0, W // 2)
    centered_in_col(d, "FOODBANKS", "receive funds", W // 2, W // 2)
    centered(d, 305, "FRAME-aligned · ESRS E1 + S3", font(13), "#57534e")
    img.save(FRAMES_DIR / "03-product.png")


def centered_in_col(d, header: str, body: str, x_start: int, w: int):
    centered_in_x(d, 215, header, font(13, bold=True), EMERALD, x_start, w)
    centered_in_x(d, 245, body, font(16), "#0c0a09", x_start, w)


def centered_in_x(d, y: int, txt: str, fnt, fill: str, x_start: int, w: int):
    tw, _ = text_size(d, txt, fnt)
    d.text((x_start + (w - tw) // 2, y), txt, fill=fill, font=fnt)


def scene_4_proof():
    img = Image.new("RGB", (W, H), WHITE)
    d = ImageDraw.Draw(img)
    # CSR report header
    d.rectangle([(40, 40), (W - 40, 90)], outline="#e7e5e4", width=1)
    centered_in_x(d, 50, "Heineken N.V. — Climate-Action Package Impact Report", font(14, bold=True), "#0c0a09", 40, W - 80)
    centered_in_x(d, 70, "Q2 2026 · Voedselbank Rotterdam", font(12), "#57534e", 40, W - 80)
    # Three big numbers
    y = 130
    col_w = (W - 80) // 3
    stats = [
        ("600.0", "tCO₂e", "avoided"),
        ("323,389", "kg", "food rescued"),
        ("7.77%", "share", "of bank annual"),
    ]
    for i, (big, unit, label) in enumerate(stats):
        x = 40 + i * col_w
        centered_in_x(d, y, big, font(34, bold=True), "#0c0a09", x, col_w)
        centered_in_x(d, y + 50, unit, font(13), "#57534e", x, col_w)
        centered_in_x(d, y + 70, label, font(11), STONE, x, col_w)
    # Footer line
    centered(d, 270, "Methodology aligned with FRAME · every figure traceable", font(13), "#57534e")
    centered(d, 295, "Generated by Claude · ready for ESRS E1 disclosure", font(13, bold=True), EMERALD)
    img.save(FRAMES_DIR / "04-proof.png")


def scene_5_traction():
    img = Image.new("RGB", (W, H), NAVY)
    d = ImageDraw.Draw(img)
    centered(d, 35, "PRE-LAUNCH TRACTION", font(13, bold=True), "#86efac")
    # Three big stats
    y = 80
    col_w = W // 3
    stats = [
        ("12", "foodbanks onboarded"),
        ("€425,000", "committed pre-launch"),
        ("7,200", "tCO₂e under contract"),
    ]
    for i, (big, label) in enumerate(stats):
        centered_in_x(d, y, big, font(36, bold=True), WHITE, i * col_w, col_w)
        centered_in_x(d, y + 55, label, font(11), STONE, i * col_w, col_w)
    # Logo wall row
    centered(d, 200, "PILOT PARTNERS", font(11, bold=True), STONE)
    centered(d, 230, "HEINEKEN  ·  MOLLIE  ·  KPN  ·  BIRD  ·  ALBERT HEIJN", font(15, bold=True), CREAM)
    centered(d, 290, "(pre-launch demo data)", font(10), "#525252")
    img.save(FRAMES_DIR / "05-traction.png")


def scene_6_close():
    img = Image.new("RGB", (W, H), EMERALD)
    d = ImageDraw.Draw(img)
    centered(d, 110, "Climate-Action Packages", font(34, bold=True), WHITE)
    centered(d, 175, "We make impact real.", font(20), "#a7f3d0")
    centered(d, 280, "climate-action-packages.eu", font(13), "#a7f3d0")
    img.save(FRAMES_DIR / "06-close.png")


def render_frames():
    FRAMES_DIR.mkdir(exist_ok=True)
    scene_1_hook()
    scene_2_insight()
    scene_3_product()
    scene_4_proof()
    scene_5_traction()
    scene_6_close()
    print(f"6 frames written to {FRAMES_DIR}")


# --- Voiceover ---
NARRATION = """Every Dutch corporate must now report verified climate impact. Most of what they claim is unverifiable. Greenwashing dressed up as compliance.

Meanwhile, Dutch foodbanks rescue forty million kilos of food a year. That's one hundred thousand tonnes of CO2 avoided. And none of it shows up on a single corporate report.

Climate-Action Packages connect them. Twenty-five thousand euros buys six hundred tonnes of CO2 equivalent. Methodology aligned with the Global Foodbanking Network's FRAME framework.

One click. Solvimon takes the payment. Claude composes the audit-ready CSR report from real foodbank data. Every figure traceable, every source cited.

Twelve foodbanks onboarded. Five corporates committed. Four hundred and twenty-five thousand euros of climate impact bought before launch.

Climate-Action Packages. We make impact real."""


def render_audio():
    AUDIO_DIR.mkdir(exist_ok=True)
    aiff = AUDIO_DIR / "narration.aiff"
    mp3 = AUDIO_DIR / "narration.mp3"
    # macOS say speaks at ~175 wpm by default — slow it slightly to 170 for clarity
    subprocess.run(
        [
            "say", "-v", "Daniel",
            "-r", "170",
            "-o", str(aiff),
            NARRATION,
        ],
        check=True,
    )
    subprocess.run(
        [
            "ffmpeg", "-y", "-loglevel", "error",
            "-i", str(aiff),
            "-codec:a", "libmp3lame",
            "-b:a", "96k",
            str(mp3),
        ],
        check=True,
    )
    duration = float(subprocess.check_output(
        ["ffprobe", "-v", "error", "-show_entries", "format=duration",
         "-of", "default=noprint_wrappers=1:nokey=1", str(mp3)]
    ).strip())
    print(f"Audio rendered: {mp3} ({duration:.1f}s)")
    return duration


# --- SRT subtitles ---
SUBS = [
    (0.0, 4.0, "Every Dutch corporate must now report verified climate impact."),
    (4.0, 8.0, "Most of what they claim is unverifiable.\nGreenwashing dressed up as compliance."),
    (8.0, 13.0, "Meanwhile, Dutch foodbanks rescue\n40 million kilos of food a year."),
    (13.0, 18.0, "100,000 tCO2e avoided —\nnone of it on a single corporate report."),
    (18.0, 23.0, "Climate-Action Packages connect them."),
    (23.0, 30.0, "€25,000 buys 600 tonnes of CO2e\n— methodology aligned with FRAME."),
    (30.0, 36.0, "One click. Solvimon takes the payment."),
    (36.0, 45.0, "Claude composes the audit-ready report —\nevery figure traceable, every source cited."),
    (45.0, 50.0, "12 foodbanks onboarded.\n5 corporates committed."),
    (50.0, 55.0, "€425,000 of climate impact\nbought before launch."),
    (55.0, 60.0, "Climate-Action Packages.\nWe make impact real."),
]


def fmt_ts(t: float) -> str:
    h = int(t // 3600)
    m = int((t % 3600) // 60)
    s = int(t % 60)
    ms = int((t - int(t)) * 1000)
    return f"{h:02d}:{m:02d}:{s:02d},{ms:03d}"


def render_srt():
    srt_path = ROOT / "subtitles.srt"
    lines = []
    for i, (start, end, text) in enumerate(SUBS, 1):
        lines.append(str(i))
        lines.append(f"{fmt_ts(start)} --> {fmt_ts(end)}")
        lines.append(text)
        lines.append("")
    srt_path.write_text("\n".join(lines))
    print(f"SRT written: {srt_path} ({len(SUBS)} cues)")
    return srt_path


# --- Scene composition: each subtitle cue gets its own pre-baked frame ---
# (this ffmpeg build lacks the subtitles filter, so we burn captions in via Pillow)
SUB_TO_SCENE = {
    1: "01-hook.png", 2: "01-hook.png",
    3: "02-insight.png", 4: "02-insight.png",
    5: "03-product.png", 6: "03-product.png",
    7: "04-proof.png", 8: "04-proof.png",
    9: "05-traction.png", 10: "05-traction.png",
    11: "06-close.png",
}


def compose_subtitled_frames():
    out_dir = FRAMES_DIR / "subtitled"
    out_dir.mkdir(exist_ok=True)
    sub_font = font(15, bold=True)
    line_spacing = 4
    box_pad = 10
    for i, (start, end, text) in enumerate(SUBS, 1):
        bg_path = FRAMES_DIR / SUB_TO_SCENE[i]
        img = Image.open(bg_path).convert("RGB")
        d = ImageDraw.Draw(img, "RGBA")
        # Compute box size
        lines = text.split("\n")
        line_dims = [text_size(d, ln, sub_font) for ln in lines]
        box_w = max(w for w, _ in line_dims) + box_pad * 2
        line_h = max(h for _, h in line_dims)
        box_h = line_h * len(lines) + line_spacing * (len(lines) - 1) + box_pad * 2
        # Position: centred horizontally, near bottom
        bx = (W - box_w) // 2
        by = H - box_h - 16
        # Draw semi-transparent black box
        d.rectangle([(bx, by), (bx + box_w, by + box_h)], fill=(0, 0, 0, 180))
        # Draw lines
        ty = by + box_pad
        for ln, (lw, _) in zip(lines, line_dims):
            d.text((bx + (box_w - lw) // 2, ty), ln, fill=(255, 255, 255), font=sub_font)
            ty += line_h + line_spacing
        out_path = out_dir / f"frame_{i:02d}.png"
        img.save(out_path)
    print(f"Composed {len(SUBS)} subtitled frames in {out_dir}")
    return out_dir


def render_video(srt_path: Path):
    sub_dir = compose_subtitled_frames()
    concat_path = ROOT / "concat.txt"
    with open(concat_path, "w") as f:
        for i, (start, end, _) in enumerate(SUBS, 1):
            duration = end - start
            f.write(f"file '{sub_dir / f'frame_{i:02d}.png'}'\n")
            f.write(f"duration {duration}\n")
        # ffmpeg concat demuxer needs the last file repeated
        f.write(f"file '{sub_dir / f'frame_{len(SUBS):02d}.png'}'\n")

    out_path = ROOT / "pitch.mp4"
    cmd = [
        "ffmpeg", "-y", "-loglevel", "error",
        "-f", "concat", "-safe", "0", "-i", str(concat_path),
        "-i", str(AUDIO_DIR / "narration.mp3"),
        "-vf", "fps=24,format=yuv420p",
        "-c:v", "libx264",
        "-profile:v", "baseline", "-level", "3.0",
        "-b:v", "500k",
        "-c:a", "aac", "-b:a", "96k",
        "-shortest",
        str(out_path),
    ]
    subprocess.run(cmd, check=True)
    size = out_path.stat().st_size
    print(f"Video rendered: {out_path} ({size / 1024:.0f} kB)")


def main():
    if not shutil.which("ffmpeg"):
        raise SystemExit("ffmpeg required")
    render_frames()
    render_audio()
    srt_path = render_srt()
    render_video(srt_path)


if __name__ == "__main__":
    main()
