"""Agent/LLM discovery endpoints: llms.txt, robots.txt, sitemap, ai-plugin manifest, health."""
from fastapi import APIRouter
from fastapi.responses import JSONResponse, PlainTextResponse, Response

router = APIRouter(tags=["discovery"])

_LLMS_TXT = """\
# Klimaatkracht

> Dutch platform connecting corporates to foodbank climate impact funds. Corporates buy impact \
packages; money is allocated to foodbanks weighted by CO₂e savings and households served. \
CSRD/ESRS E5-compliant reports generated via Claude.

## API

- [OpenAPI spec](/openapi.json): Full REST API — packages, checkout, dashboard, reporting
- [Packages](/packages): List available impact packages (public, no auth)
- [Aggregate stats](/insights/aggregate): Platform-wide tCO₂e, kg rescued, households (public)
- [Foodbank list](/insights/banks): All foodbanks with FRAME CO₂e data and coordinates (public)
- [Register](/auth/register): Create a corporate account
- [Login](/auth/login): Authenticate and get session cookie

## Authenticated endpoints (cookie session)

- [Dashboard](/dashboard): List your subscriptions with CO₂e attribution
- [Checkout](/packages/{id}/checkout): Subscribe to an impact package (POST)
- [Generate report](/report/{sub_id}/generate): Trigger CSRD/ESRS E5 report generation (POST)
- [Stream report](/report/{sub_id}/stream): Stream SSE report chunks (GET)
- [Download report](/report/{sub_id}/download): Download final markdown report (GET)

## Optional

- [Admin — foodbank list](/admin/foodbanks): Admin-role only
"""

_LLMS_FULL_TXT = """\
# Klimaatkracht — Full API Reference

> Dutch impact investment platform. Corporates subscribe to packages that fund Dutch foodbanks \
proportionally to their verified CO₂e savings (FRAME methodology) and/or households served. \
Reports are CSRD/ESRS E5 compliant, generated by Claude Sonnet streaming via SSE.

## Authentication

Cookie-based sessions. Register at `POST /auth/register`, login at `POST /auth/login`. \
Session cookie (`session`) is set automatically. TTL: 7 days.

### Register
`POST /auth/register`
Body: `{"email": str, "password": str, "org_name": str, "role": "corporate"|"admin"}`
Returns: `{"id", "email", "org_name", "role"}`

### Login
`POST /auth/login`
Body: `{"email": str, "password": str}`
Returns: `{"id", "email", "org_name", "role"}` + sets session cookie

### Me
`GET /auth/me` — current user info (requires auth)

### Logout
`POST /auth/logout` — clears session cookie

## Packages (public)

### List packages
`GET /packages?profile=co2_focus|social_focus|balanced`
Returns: list of `{id, name, description, region, price_eur, co2e_claim_kg, impact_profile, top_n, is_active}`

### Get package
`GET /packages/{package_id}`

## Checkout (requires auth)

### Create subscription
`POST /packages/{package_id}/checkout`
Returns: `{id, user_id, package_id, amount_eur, status}`
Status starts as `pending`.

### Confirm payment (mock)
`GET /checkout/{sub_id}/confirm`
Transitions status to `confirmed`, triggers allocation computation.

## Dashboard (requires auth)

### List subscriptions
`GET /dashboard`
Returns: list of `{id, package_id, package_name, amount_eur, status, total_co2e_kg}`

### Subscription detail
`GET /dashboard/{sub_id}`
Returns: subscription + `allocations: [{foodbank_id, foodbank_name, foodbank_city, weight_pct, amount_eur, co2e_attributed_kg}]`

## Reports (requires auth)

### Generate report
`POST /report/{sub_id}/generate`
Returns: `{sub_id, stream_url}`

### Stream report (SSE)
`GET /report/{sub_id}/stream`
Content-Type: `text/event-stream`. Streams Claude-generated CSRD/ESRS E5 markdown chunks.

### Download report
`GET /report/{sub_id}/download`
Returns the saved markdown report file.

## Insights (public)

### Aggregate platform stats
`GET /insights/aggregate`
Returns: `{banks_count, total_tco2e_yr, total_kg_rescued_yr, total_households_wk}`

### All foodbanks
`GET /insights/banks`
Returns: list of foodbanks with latest FRAME data, coordinates, category CO₂e breakdown.

### Single foodbank
`GET /insights/banks/{bank_id}`

## Optional

- `GET /admin/foodbanks` — admin role required
- `GET /openapi.json` — machine-readable OpenAPI 3.1 spec
- `GET /docs` — Swagger UI
- `GET /redoc` — ReDoc UI
"""

_ROBOTS_TXT = """\
User-agent: *
Allow: /

# AI/LLM crawlers — full access to public API and docs
User-agent: GPTBot
Allow: /

User-agent: ChatGPT-User
Allow: /

User-agent: ClaudeBot
Allow: /

User-agent: anthropic-ai
Allow: /

User-agent: Claude-Web
Allow: /

User-agent: PerplexityBot
Allow: /

User-agent: Amazonbot
Allow: /

User-agent: cohere-ai
Allow: /

Sitemap: /sitemap.xml
"""

_SITEMAP_XML = """\
<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url><loc>/openapi.json</loc></url>
  <url><loc>/llms.txt</loc></url>
  <url><loc>/llms-full.txt</loc></url>
  <url><loc>/packages</loc></url>
  <url><loc>/insights/aggregate</loc></url>
  <url><loc>/insights/banks</loc></url>
  <url><loc>/docs</loc></url>
</urlset>
"""

_AI_PLUGIN = {
    "schema_version": "v1",
    "name_for_human": "Klimaatkracht",
    "name_for_model": "klimaatkracht",
    "description_for_human": (
        "Invest in Dutch foodbank climate impact. Browse packages, subscribe, "
        "track CO₂e attribution across foodbanks, and generate CSRD reports."
    ),
    "description_for_model": (
        "Klimaatkracht REST API. Dutch corporates subscribe to impact packages that fund "
        "foodbanks proportionally to their verified CO₂e savings (FRAME methodology) and "
        "households served. Public endpoints: GET /packages, GET /insights/aggregate, "
        "GET /insights/banks. Authenticated (cookie session): POST /auth/register, "
        "POST /auth/login, POST /packages/{id}/checkout, GET /dashboard, "
        "POST /report/{sub_id}/generate, GET /report/{sub_id}/stream (SSE), "
        "GET /report/{sub_id}/download. Reports are CSRD/ESRS E5 compliant markdown, "
        "generated by Claude Sonnet and streamed as server-sent events."
    ),
    "auth": {"type": "user_http", "authorization_type": "cookie"},
    "api": {"type": "openapi", "url": "/openapi.json"},
    "contact_email": "contact@klimaatkracht.nl",
    "legal_info_url": "/legal",
}

_AGENT_JSON = {
    "name": "Klimaatkracht",
    "version": "1.0.0",
    "description": (
        "Platform connecting Dutch corporates to foodbank climate impact funds. "
        "Exposes a REST API (OpenAPI 3.1) for package discovery, subscription, "
        "CO₂e impact attribution, and CSRD/ESRS E5 report generation."
    ),
    "url": "/",
    "api": {"type": "openapi", "url": "/openapi.json"},
    "capabilities": ["packages", "checkout", "impact-attribution", "csrd-reporting"],
    "authentication": {
        "type": "cookie",
        "login_url": "/auth/login",
        "register_url": "/auth/register",
    },
    "llms_txt": "/llms.txt",
    "llms_full_txt": "/llms-full.txt",
}


@router.get("/health", summary="Health check")
def health() -> dict:
    """Returns `{status: ok}`. No auth required."""
    return {"status": "ok"}


@router.get("/llms.txt", include_in_schema=False)
def llms_txt() -> PlainTextResponse:
    return PlainTextResponse(_LLMS_TXT, media_type="text/plain; charset=utf-8")


@router.get("/llms-full.txt", include_in_schema=False)
def llms_full_txt() -> PlainTextResponse:
    return PlainTextResponse(_LLMS_FULL_TXT, media_type="text/plain; charset=utf-8")


@router.get("/robots.txt", include_in_schema=False)
def robots_txt() -> PlainTextResponse:
    return PlainTextResponse(_ROBOTS_TXT, media_type="text/plain; charset=utf-8")


@router.get("/sitemap.xml", include_in_schema=False)
def sitemap_xml() -> Response:
    return Response(_SITEMAP_XML, media_type="application/xml")


@router.get("/.well-known/ai-plugin.json", include_in_schema=False)
def ai_plugin() -> JSONResponse:
    return JSONResponse(_AI_PLUGIN)


@router.get("/.well-known/agent.json", include_in_schema=False)
def agent_json() -> JSONResponse:
    return JSONResponse(_AGENT_JSON)
