"use client"

import { useEffect, useRef, useState } from "react"
import ReactMarkdown from "react-markdown"
import remarkGfm from "remark-gfm"
import { Badge } from "@/components/ui/Badge"
import { api } from "@/lib/api"

type Phase = "idle" | "streaming" | "done" | "error"

export function ReportStream({ subId }: { subId: string }) {
  const [text, setText] = useState("")
  const [phase, setPhase] = useState<Phase>("idle")
  const esRef = useRef<EventSource | null>(null)

  useEffect(() => {
    const buf: string[] = []
    setPhase("streaming")
    const es = new EventSource(api.reportStreamUrl(subId), { withCredentials: true })
    esRef.current = es

    es.onmessage = (e) => {
      const data = e.data
      if (data === "[DONE]") {
        setPhase("done")
        es.close()
        return
      }
      if (data.startsWith("[ERROR]")) {
        setPhase("error")
        es.close()
        return
      }
      // Backend escapes newlines as literal \n in SSE; restore them.
      const decoded = data.replace(/\\n/g, "\n")
      buf.push(decoded)
      setText(buf.join(""))
    }
    es.onerror = () => {
      setPhase("error")
      es.close()
    }
    return () => {
      es.close()
    }
  }, [subId])

  return (
    <div className="border border-line rounded-[var(--radius-lg)] bg-surface">
      <div className="px-6 py-4 border-b border-line/60 flex items-center gap-3">
        <PhaseBadge phase={phase} />
        <span className="text-[12.5px] text-text-faint tabular">
          generated by claude-sonnet-4-6
        </span>
        <a
          href={api.reportDownloadUrl(subId)}
          className="ml-auto text-[13px] text-emerald hover:underline"
        >
          Download .md
        </a>
      </div>
      <article className="px-8 py-8 prose prose-stone max-w-none">
        {text ? (
          <ReactMarkdown remarkPlugins={[remarkGfm]}>{text}</ReactMarkdown>
        ) : (
          <p className="text-text-muted">Waiting for the first chunk…</p>
        )}
      </article>
    </div>
  )
}

function PhaseBadge({ phase }: { phase: Phase }) {
  if (phase === "streaming") return <Badge variant="emerald">Streaming</Badge>
  if (phase === "done") return <Badge variant="emerald">Complete</Badge>
  if (phase === "error") return <Badge variant="warning">Error</Badge>
  return <Badge variant="default">Idle</Badge>
}
