import Link from "next/link"
import { use } from "react"
import { ReportStream } from "@/components/report/ReportStream"

export default function ReportPage({ params }: { params: Promise<{ subId: string }> }) {
  const { subId } = use(params)
  return (
    <div className="mx-auto max-w-[920px] px-6 pt-12 pb-24">
      <Link href="/dashboard/corporate" className="text-[13px] text-text-muted hover:text-text">
        ← Back to dashboard
      </Link>
      <p className="eyebrow mt-6">ESRS E5 + S3 · contribution disclosure</p>
      <h1 className="display text-5xl mt-3 tracking-[-0.025em] max-w-[20ch]">
        Quarterly contribution report.
      </h1>
      <p className="text-text-muted text-[14.5px] mt-5 max-w-[58ch] leading-relaxed">
        Generated by Claude from the FRAME workings, allocation breakdown, and source
        citations of every food bank in this subscription. Climate contribution claim,
        not an offset against the buyer&apos;s ESRS&nbsp;E1 footprint.
      </p>
      <div className="mt-10">
        <ReportStream subId={subId} />
      </div>
    </div>
  )
}
